trigger:
-   master

pool:
    vmImage: 'ubuntu-16.04'

steps:
-   script: |
        echo installing gauge
        sudo apt-key adv --keyserver hkp://pool.sks-keyservers.net --recv-keys 023EDB0B
        echo deb https://dl.bintray.com/gauge/gauge-deb stable main | sudo tee -a /etc/apt/sources.list
        sudo apt-get update
        sudo apt-get install gauge
        sudo npm install
        sudo taiko -v
    displayName: 'install gauge and taiko'

-   script: |
        echo starting gauge test
        npm test
    displayName: 'gauge test'